### ISSUE TITLE
Made changes to the Github Issue to fix a few tables and include some ABC Data and a meme

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-backend#55]
Edited this issue
https://github.com/CommonsBuild/test-issues-config-dashboard/issues/235

- [x] Added a meme at the beginning to inspire more memes
- [x] moved Advanced Settings Modified? down
- [x] changed the fork proposal link everywhere
- [x] Disputable Voting was still used, switched it to Tao Voting
- [x] fixed the token freeze table to have months and years (should be shown completely no need to cut off the table like in the dashboard)
- [x] added the 3rd step as Pedro noted in #45 
- [x] added the ABC Configuration Table
- [x] Changed the Tao voting table to make it more useful and correct (the extension days were not correct!) see #54
- [x] Changed the hours to days for execution delay see #57 
- [x] Transposed the table in the CV module see #50 
- [x] changed Transferability to Transferable and true to  Yes

**Comment by GriffGreen** [comment]
| Proposal  | Requested Amount (wxDAI) | Common Pool (wxDAI) | Effective supply (TEC) | Tokens Needed To Pass (TEC) |
|:---------:|:------------------------:|:-------------------:|:----------------------:|:---------------------------:|
|     1     |           1,000          |       100,000       |        1,500,000       |            50,784           |
|     2     |           5,000          |       100,000       |        1,500,000       |           164,543           |
|     3     |          25,000          |       100,000       |        1,500,000       |         Not possible        |
|     4     |           1,000          |       750,000       |        1,500,000       |            42,254           |
|     5     |           5,000          |       750,000       |        1,500,000       |            47,221           |
|     6     |          25,000          |       750,000       |        1,500,000       |            92,554           |

**Comment by GriffGreen** [comment]
| Reserve (wxDai)     | Supply (TEC)       | Price (wxDai/TEC) |
| ------------------- | ------------------ | ----------------- |
| 10,000  | #  | #  |
| 50,000  | #  | #  |
| 100,000  | 1,342,662  | 0.37  |
| 200,000  | 1,541,817  | 0.65  |
| 300,000  | 1,671,744  | 0.90  |
| 400,000  | 1,770,515  | 1.13  |
| 500,000  | 1,851,130  | 1.35  |
| 600,000  | #  | #  |
| 700,000  | #  | #  |
| 800,000  | #  | #  |
| 900,000  | #  | #  |
| 1,000,000  | 2,125,710  | 2.36  |
| 1,250,000  | 2,222,497  | 2.82  |
| 1,500,000  | 2,304,841  | 3.26  |
| 1,750,000  | 2,304,841  | 3.26  |
| 2,000,000  | 2,441,018  | 4.11  |
| 2,500,000 | 2,552,163 | 4.91 |
| 3,000,000 | 2,646,721 | 5.68 |
| 3,500,000 | # | # |
| 4,000,000 | 2,803,098 | 7.15 |
| 5,000,000 | 2,930,728 | 8.55 |
| 7,500,000 | 3,177,698 | 11.83 |
| 10,000,000 | 3,365,447 | 14.89 |
| 15,000,000 | 3,649,050 | 20.60 |
| 20,000,000 | 3,864,648 | 25.94 |
| 50,000,000 | 4,639,962 | 54.00 |
| 100,000,000 | # | # |
